name: Publish Docker images (slim & full) on tag
on:
  push:
    tags:
      - 'v*'   # e.g., v0.1.0

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # allows pushing to GHCR with GITHUB_TOKEN
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build & push SLIM
      - name: Build & push slim
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.slim
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/cpp-studio:slim
            ghcr.io/${{ github.repository_owner }}/cpp-studio:${{ github.ref_name }}-slim

      # Build & push FULL
      - name: Build & push full
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/cpp-studio:full
            ghcr.io/${{ github.repository_owner }}/cpp-studio:${{ github.ref_name }}-full
