name: Manifest Consistency

on:
  pull_request:
  workflow_dispatch:

jobs:
  manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (csv)
        run: python -m pip install --upgrade pip pandas

      - name: Run manifest check
        run: |
          python .github/scripts/check_manifest.py
